# Generated by Django 3.2.6 on 2021-09-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
