# Generated by Django 3.2.6 on 2021-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_date',
            new_name='date_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date_published',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
