# Generated by Django 3.2.6 on 2021-09-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210915_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_published',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_modified',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_modified',
            new_name='update_date',
        ),
    ]
