# Generated by Django 3.2.6 on 2021-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCodeBlog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
