# Generated by Django 3.2.6 on 2021-08-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weCodeBlog', '0006_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='tags',
        ),
    ]
